import { Providers } from "@/lib/provider";
import "./globals.css";

export const metadata = {
  title: "Mini Ecommerce",
  description: "Generated by Pijmo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
